server:
  port: ${PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
  config:
    name: ConfigServer
  application:
    name: ConfigServer