version: '3'
services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
  mypostgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=matriz
  ui:
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      - app
  