version: '2'
services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
  ui:
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      - app
  mypostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=matriz