jwt:
  expirationInMs: 604800000
  secret: secretKey
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
